- name: pru
  hosts: localhost
  become: true  
  connection: local
  gather_facts: false
  
  
  vars:
    aws_region: "eu-west-1"
    
  tasks:
    - name: list aws instenaces
      ec2_instance_facts:
        region: "{{ aws_region }}"
      register: ec2_facts

