---
- name: Install {{ app-tier }}
  package:
#  yum:
    name: "{{ app-tier }}"
    state: latest

- name: enable {{ app-tier }} at boot
  service:
    name: "{{ app-tier }}"
    enabled: yes

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  notify: restart {{ app-tier }}
